// Loader for the pre-baked region monsters generated by
// `npm run gen:monsters`. Returns a map { regionId -> monster | null }.
// Misses (asset not generated yet) resolve to null so callers can fall back
// to live Gemini generation.

const BASE = import.meta.env.BASE_URL || "/";

export async function loadBakedMonster(regionId) {
  try {
    const res = await fetch(`${BASE}monsters/${regionId}.json`, { cache: "force-cache" });
    if (!res.ok) return null;
    const m = await res.json();
    if (!m || !m.name || !m.imageDataUrl) return null;
    // Ensure each load gets a fresh id so React keys don't collide if the
    // same baked monster is used across separate slots/sessions.
    return { ...m, id: `${m.id}_${Math.random().toString(36).slice(2, 6)}` };
  } catch {
    return null;
  }
}

export async function loadBakedMonsters(regionIds) {
  const entries = await Promise.all(
    regionIds.map(async id => [id, await loadBakedMonster(id)]),
  );
  return Object.fromEntries(entries);
}
